services:
  postgres:
    image: postgres:13
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    build:
      context: ..
      dockerfile: docker/Dockerfile.keycloak
    container_name: keycloak
    environment:
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Development settings
      KC_LOG_LEVEL: INFO
    ports:
      - "3220:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network

  telegram-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.telegram-bot
    container_name: telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data: